name: Go

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [ "main" ]
    tags:
      - 'v*.*.*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set Versioning Tag Name
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.0'

    - name: Build (x64)
      run: GOOS=windows && GOARCH=amd64 && go build -o timer.exe main.go
        
    - name: Publish Release
      uses: softprops/action-gh-release@v2.2.1
      with:
        files: timer.exe
        name: ${{ env.RELEASE_VERSION }}
        tag_name: ${{ env.RELEASE_VERSION }}
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}        
